### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by vaaski** [vaaski/vaaski.dev#1]
## general
- [ ] add link to page source
- [ ] style checkboxes
## minifier
- [ ] add examples/toolkit

---
<details>
<summary>resolved</summary>

- [x] make it a pwa with offline support
- [x] add clear button for codearea
- [x] disable spellcheck for bookmark name
- [x] split babel into smaller chunks and lazy load them
- [x] show before & after bytesize
- [x] make minify-mangle-names work when transpile and iife are enabled
- [x] save settings and maybe the code too
- [x] netlify server conf for history mode
- [x] add transpile option
</details>
